### ISSUE TITLE
Nature drive content

### ISSUE THREAD

**Issue by mantl002** [hiltaba/hiltaba.github.io#22]
Hiltaba offers two fantastic nature drives:
 - Mt St. Mungo (~3 hours) 
 - Pine Well (~4 hours)
It is important to note these nature drives require a 4WD vehicle. 

The St. Mungo drive takes visitors off Hiltaba road and through the retired cattle yards and grazing areas through to the Pretty Point Camp Ground. The dams and water wells from Hiltabas previous life can be observed along the way.  Waypoint 5 on the St Mungo Drive Alpaca map shown above indicates the start of an optional walk to the summit of Mt St. Mungo.

The Pine Well nature drive features magnificent views of the reserve while passing by a retired Sheep Shearing Shed, Narlaby Well and Punkey Dam. **The rare Orchid only found in Hiltaba can also be seen.**

**Comment by JoshGore** [comment]
St. Mungo drive provides views of Hiltaba’s retired cattle yards, wells, and dams. A short walk up to the peak of St. Mungo yields stunning 360-degree views.

**Comment by stevenkeefe** [comment]
**St. Mungo**
The St. Mungo Nature Drive takes visitors off Hiltaba road and through the retired cattle yards and grazing areas through to the Pretty Point Camp Ground. The dams and water wells from Hiltabas previous life can be observed along the way. Waypoint 5 on the St Mungo Drive Alpaca map shown above indicates the start of an optional walk to the summit of Mt St. Mungo. St Mungo Nature Drive is approximately 79 kilometres long and is an easy to moderate nature drive. While drive along St. Mungo Nature Drive you will come across basic signs that shows the direction of flow, geological features and other interesting features. Sections of the St. Mungo Drive is suitable for conventual vehicles with good ground clearance, but the Lookout section of the nature drive should only be completed by 4WD vehicles. Before commencing the Nature Drive ensure that the correct precautions have been undertaken and all fees have been payed.

**Pine Well**
The Pine Well Nature Drive features magnificent views of the reserve while passing by a retired Sheep Shearing Shed, Narlaby Well and Punkey Dam. The nature drive includes the passing of a rare Orchid that can only found in Hiltaba Nature Reserve. The Pine Well Nature Drive is approximately 77 kilometres in length and in an easy to moderate drive. Pine Well Nature Drive is only suitable for 4WD vehicles due to the uneven terrain and exposed rocks. While undertaking the Pine Well Nature Drive you will come across basic signs that shows the direction of flow, geological features and other interesting features. Before commencing the Nature Drive ensure that the correct precautions have been undertaken and all fees have been payed. 

Possible structure like home page and include an image each

**Comment by stevenkeefe** [comment]
**Tag Along Tour**
Hiltaba Nature Reserve also offer additional services on both Nature Drives in the form of a guided tour. The manager of Hiltaba Nature Reserve will provide Tag Along Tour and take you through the heart of Hiltaba to experience and learn what makes Hiltaba Nature Reserve the jewel of the Gawler Ranges. Booking and additional fees and charges may apply.
